name: Rerun everyday at 10:25AM on a CRON Schedule

on:
  workflow_dispatch:
  schedule:
    # Runs "at 10:25AM every day"
    - cron: '25 8 * * *'
jobs:
  build:
    name: Pull requests handler
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
      - name: execute py script # run script
        run: python github_stats.py --repo https://github.com/python/cpython --token ${{ secrets.TOKEN_GITHUB }} --format table